name: post_processing_agent_py3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - plotly
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-mock
  - requests
  - twisted
  - pip: # will need to be installed separately if pip is broken
    - stompest
# needed for wheel - add when switching to python3
#  - build
