name: post_processing_agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - plotly
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-mock
  - requests=2.25
  - stomp.py=7
  - h5py
  - build
  - psutil
