name: post_processing_agent_py3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - plotly
  - pytest
  - pytest-cov
  - pytest-mock
  - requests
  - twisted
  - pip: # will need to be installed separately if pip is broken
    - twisted==12.2.0
    - stompest==2.1.6
    - stompest-async==2.1.6
# needed for wheel - add when switching to python3
#  - build
