name: post_processing_agent
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py
  - plotly
  - pre-commit
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.9
  - python-build
  - requests=2.25
  - stomp.py=7
